#!/bin/bash

# Agent Context Protocol (ACP) Installation Script
# This script sets up the ACP directory structure and template files in a project

set -e

# Colors for output using tput (more reliable than ANSI codes)
if command -v tput >/dev/null 2>&1 && [ -t 1 ]; then
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    BOLD=$(tput bold)
    NC=$(tput sgr0)
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    BOLD=''
    NC=''
fi

# Repository details
REPO_URL="https://github.com/prmichaelsen/agent-context-protocol.git"
BRANCH="mainline"

echo "${GREEN}Agent Context Protocol (ACP) Installer${NC}"
echo "========================================"
echo ""

# Use current directory
TARGET_DIR="$(pwd)"

echo "Installing ACP to: $TARGET_DIR"
echo ""

# Check if agent directory already exists
if [ -d "$TARGET_DIR/agent" ]; then
    echo "${YELLOW}Note: agent/ directory already exists${NC}"
    echo "All ACP files will be updated to latest versions."
    echo ""
fi

# Create temporary directory
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

echo "Cloning ACP repository..."
if ! git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$TEMP_DIR" &>/dev/null; then
    echo "${RED}Error: Failed to clone repository${NC}"
    echo "Please check your internet connection and try again."
    exit 1
fi

echo "${GREEN}✓${NC} Repository cloned"
echo ""

# Create directory structure
echo "Creating directory structure..."
mkdir -p "$TARGET_DIR/agent/design"
mkdir -p "$TARGET_DIR/agent/milestones"
mkdir -p "$TARGET_DIR/agent/patterns"
mkdir -p "$TARGET_DIR/agent/tasks"
mkdir -p "$TARGET_DIR/agent/commands"
mkdir -p "$TARGET_DIR/agent/scripts"
mkdir -p "$TARGET_DIR/agent/schemas"
mkdir -p "$TARGET_DIR/agent/reports"
mkdir -p "$TARGET_DIR/agent/drafts"
mkdir -p "$TARGET_DIR/agent/clarifications"
mkdir -p "$TARGET_DIR/agent/feedback"
mkdir -p "$TARGET_DIR/agent/preferences"

# Create .gitkeep files
touch "$TARGET_DIR/agent/design/.gitkeep"
touch "$TARGET_DIR/agent/milestones/.gitkeep"
touch "$TARGET_DIR/agent/patterns/.gitkeep"
touch "$TARGET_DIR/agent/tasks/.gitkeep"
touch "$TARGET_DIR/agent/clarifications/.gitkeep"

# Create agent/.gitignore to exclude local-only directories from version control
cat > "$TARGET_DIR/agent/.gitignore" << 'EOF'
# Agent Context Protocol - Local Files
# These files are generated locally and should not be committed

# Reports directory - generated by @acp.report command
reports/
clarifications/
feedback/
drafts/
preferences/
EOF

echo "${GREEN}✓${NC} Directory structure created"
echo ""

# Copy files
echo "Installing ACP files..."

# Copy template files (only .template.md files from these directories)
find "$TEMP_DIR/agent/design" -maxdepth 1 -name "*.template.md" -exec cp {} "$TARGET_DIR/agent/design/" \;
find "$TEMP_DIR/agent/milestones" -maxdepth 1 -name "*.template.md" -exec cp {} "$TARGET_DIR/agent/milestones/" \;
find "$TEMP_DIR/agent/patterns" -maxdepth 1 -name "*.template.md" -exec cp {} "$TARGET_DIR/agent/patterns/" \;
find "$TEMP_DIR/agent/tasks" -maxdepth 1 -name "*.template.md" -exec cp {} "$TARGET_DIR/agent/tasks/" \;
find "$TEMP_DIR/agent/clarifications" -maxdepth 1 -name "*.template.md" -exec cp {} "$TARGET_DIR/agent/clarifications/" \;

# Copy command template
cp "$TEMP_DIR/agent/commands/command.template.md" "$TARGET_DIR/agent/commands/"

# Copy all command files (flat structure with dot notation)
# Copies files like acp.init.md, acp.status.md, deploy.production.md, etc.
if [ -d "$TEMP_DIR/agent/commands" ]; then
    find "$TEMP_DIR/agent/commands" -maxdepth 1 -name "*.*.md" -exec cp {} "$TARGET_DIR/agent/commands/" \;
fi

# Copy progress template
if [ -f "$TEMP_DIR/agent/progress.template.yaml" ]; then
    cp "$TEMP_DIR/agent/progress.template.yaml" "$TARGET_DIR/agent/"
fi

# Copy manifest template
if [ -f "$TEMP_DIR/agent/manifest.template.yaml" ]; then
    cp "$TEMP_DIR/agent/manifest.template.yaml" "$TARGET_DIR/agent/"
fi

# Copy package template
if [ -f "$TEMP_DIR/agent/package.template.yaml" ]; then
    cp "$TEMP_DIR/agent/package.template.yaml" "$TARGET_DIR/agent/"
fi

# Create initial manifest.yaml if it doesn't exist
if [ ! -f "$TARGET_DIR/agent/manifest.yaml" ]; then
    cat > "$TARGET_DIR/agent/manifest.yaml" << 'EOF'
# ACP Package Manifest
# Tracks installed packages and their versions

packages: {}

manifest_version: 1.0.0
last_updated: null
EOF
fi

# Copy schemas
if [ -f "$TEMP_DIR/agent/schemas/package.schema.yaml" ]; then
    cp "$TEMP_DIR/agent/schemas/package.schema.yaml" "$TARGET_DIR/agent/schemas/"
fi

# Copy AGENT.md
cp "$TEMP_DIR/AGENT.md" "$TARGET_DIR/"

# Copy scripts - selective installation based on command dependencies
if [ -d "$TEMP_DIR/agent/scripts" ]; then
    # Check if this is ACP core (has package.yaml) or direct install
    if [ -f "$TEMP_DIR/package.yaml" ]; then
        # ACP core with package.yaml - selective script installation
        echo "Resolving script dependencies from package.yaml..."
        
        # Copy YAML parser first (needed for parsing)
        if [ -f "$TEMP_DIR/agent/scripts/acp.yaml-parser.sh" ]; then
            cp "$TEMP_DIR/agent/scripts/acp.yaml-parser.sh" "$TARGET_DIR/agent/scripts/"
            chmod +x "$TARGET_DIR/agent/scripts/acp.yaml-parser.sh"
        fi
        
        # Copy common utilities first (needed for parsing)
        if [ -f "$TEMP_DIR/agent/scripts/acp.common.sh" ]; then
            cp "$TEMP_DIR/agent/scripts/acp.common.sh" "$TARGET_DIR/agent/scripts/"
            chmod +x "$TARGET_DIR/agent/scripts/acp.common.sh"
        fi
        
        # Source YAML parser for querying
        if [ -f "$TARGET_DIR/agent/scripts/acp.yaml-parser.sh" ]; then
            . "$TARGET_DIR/agent/scripts/acp.yaml-parser.sh"
            yaml_parse "$TEMP_DIR/package.yaml"
        fi
        
        # Find all NON-experimental commands in package (or all if no experimental filtering)
        PACKAGE_COMMANDS=()
        while IFS= read -r cmd; do
            if [ -n "$cmd" ] && [ "$cmd" != "null" ]; then
                # Check if command is experimental
                is_exp=$(yaml_query ".contents.commands[] | select(.name == \"$cmd\") | .experimental?" 2>/dev/null || echo "false")
                if [ "$is_exp" != "true" ]; then
                    PACKAGE_COMMANDS+=("$cmd")
                fi
            fi
        done < <(yaml_query ".contents.commands[].name" 2>/dev/null || echo "")
        
        # Collect required scripts from non-experimental commands
        REQUIRED_SCRIPTS=()
        for cmd in "${PACKAGE_COMMANDS[@]}"; do
            # Read scripts array from package.yaml for this command
            cmd_scripts=$(yaml_query ".contents.commands[] | select(.name == \"$cmd\") | .scripts[]?" 2>/dev/null || echo "")
            
            # Add each script to required list (with deduplication)
            while IFS= read -r script; do
                if [ -n "$script" ] && [ "$script" != "null" ]; then
                    # Check if already in list
                    already_added=false
                    for existing in "${REQUIRED_SCRIPTS[@]}"; do
                        if [ "$existing" = "$script" ]; then
                            already_added=true
                            break
                        fi
                    done
                    
                    if [ "$already_added" = false ]; then
                        REQUIRED_SCRIPTS+=("$script")
                    fi
                fi
            done <<< "$cmd_scripts"
        done
        
        # Install required scripts (excluding common.sh and yaml-parser.sh already copied)
        for script in "${REQUIRED_SCRIPTS[@]}"; do
            if [ "$script" = "acp.common.sh" ] || [ "$script" = "acp.yaml-parser.sh" ]; then
                continue  # Already copied
            fi
            
            if [ -f "$TEMP_DIR/agent/scripts/$script" ]; then
                # Check if script is experimental
                is_exp=$(yaml_query ".contents.scripts[] | select(.name == \"$script\") | .experimental?" 2>/dev/null || echo "false")
                if [ "$is_exp" != "true" ]; then
                    cp "$TEMP_DIR/agent/scripts/$script" "$TARGET_DIR/agent/scripts/"
                    chmod +x "$TARGET_DIR/agent/scripts/$script"
                fi
            fi
        done
        
        echo "${GREEN}✓${NC} Installed ${#REQUIRED_SCRIPTS[@]} required script(s)"
    else
        # Direct install mode (no package.yaml) - copy all scripts
        find "$TEMP_DIR/agent/scripts" -maxdepth 1 -name "*.sh" -exec cp {} "$TARGET_DIR/agent/scripts/" \;
        chmod +x "$TARGET_DIR/agent/scripts"/*.sh 2>/dev/null || true
        echo "${GREEN}✓${NC} Installed all scripts"
    fi
fi

# Clean up deprecated scripts (from versions < 2.0.0)
. "$TARGET_DIR/agent/scripts/acp.common.sh"
init_colors
cleanup_deprecated_scripts

echo "${GREEN}✓${NC} All files installed"
echo ""

# Create manifest.yaml to track core ACP installation
echo "Creating manifest..."

# Get ACP version from AGENT.md
ACP_VERSION=$(grep "^\*\*Version\*\*:" "$TARGET_DIR/AGENT.md" | sed 's/.*: //' | head -1)
INSTALL_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# List installed core files
CORE_COMMANDS=$(cd "$TARGET_DIR" && ls agent/commands/acp.*.md agent/commands/git.*.md 2>/dev/null | xargs -n1 basename)
CORE_PATTERNS=$(cd "$TARGET_DIR" && ls agent/patterns/*.template.md 2>/dev/null | xargs -n1 basename)
CORE_DESIGNS=$(cd "$TARGET_DIR" && ls agent/design/*.template.md 2>/dev/null | xargs -n1 basename)

# Create manifest with acp-core package
cat > "$TARGET_DIR/agent/manifest.yaml" << EOF
# ACP Package Manifest
# Tracks installed packages and their versions

packages:
  acp-core:
    source: https://github.com/prmichaelsen/agent-context-protocol.git
    package_version: ${ACP_VERSION}
    installed_at: ${INSTALL_DATE}
    updated_at: ${INSTALL_DATE}
    files:
      commands:
$(echo "$CORE_COMMANDS" | sed 's/^/        - name: /')
      patterns:
$(echo "$CORE_PATTERNS" | sed 's/^/        - name: /')
      designs:
$(echo "$CORE_DESIGNS" | sed 's/^/        - name: /')

manifest_version: 1.0.0
last_updated: ${INSTALL_DATE}
EOF

echo "${GREEN}✓${NC} Created manifest.yaml (tracking acp-core v${ACP_VERSION})"
echo ""
echo "${GREEN}Installation complete!${NC}"
echo ""
echo "${GREEN}Next steps:${NC}"
echo "1. Create your requirements document:"
echo "   cp agent/design/requirements.template.md agent/design/requirements.md"
echo ""
echo "2. Define your first milestone:"
echo "   cp agent/milestones/milestone-1-{title}.template.md agent/milestones/milestone-1-foundation.md"
echo ""
echo "3. Initialize progress tracking:"
echo "   cp agent/progress.template.yaml agent/progress.yaml"
echo ""
echo "4. Read AGENT.md for complete documentation"
echo ""
display_available_commands
echo ""
echo "${BLUE}For AI agents:${NC}"
echo "Type '${GREEN}@acp.init${NC}' to get started."
echo ""
